name: Hello World

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello from Kulziya"
      - name: Operating System
        run: uname -a
      - name: Current Directory
        run: pwd
